import { Database, Scale, ShieldCheck, UserRoundCheck } from "lucide-react";
import { Link } from "react-router-dom";
import { PageHeader } from "../components/PageHeader";

const themes = [
  ["Public transparency", "MPLADS AI makes the active dataset easier to explore through searchable, dataset-derived public views.", Database],
  ["Analytical context", "The platform presents actual implementation, financial and lifecycle patterns where the source supports them; it does not manufacture gaps in the record.", Scale],
  ["Careful interpretation", "Missing information is identified as unavailable rather than treated as zero, completion or proof of anything.", ShieldCheck],
  ["Human review", "AI identifies signals; authorized officials make the final decision.", UserRoundCheck],
] as const;

export default function AboutPage() {
  return <div className="space-y-8"><PageHeader eyebrow="About MPLADS AI" title="A public data experience built around traceability" description="MPLADS AI is an independent analytical interface for exploring supplied MPLADS datasets. It is not an official Government of India portal." /><section className="grid gap-4 md:grid-cols-2">{themes.map(([title, content, Icon]) => <article key={title} className="rounded-xl border border-line bg-white p-6"><Icon className="size-5 text-blue" aria-hidden="true" /><h2 className="mt-4 text-lg font-semibold text-ink">{title}</h2><p className="mt-2 leading-7 text-slate-600">{content}</p></article>)}</section><section className="rounded-xl border border-line bg-white p-6"><h2 className="text-xl font-semibold text-ink">Methodology &amp; transparency</h2><div className="mt-5 grid gap-6 lg:grid-cols-2"><div><h3 className="font-semibold text-ink">How public views are produced</h3><ol className="mt-3 list-decimal space-y-2 pl-5 text-sm leading-6 text-slate-700"><li>Supplied source datasets are inspected, staged and validated.</li><li>Resolvable records are linked to canonical work identities.</li><li>Financial values are aggregated from source transactions, and lifecycle views show only supported linked records.</li><li>The FastAPI analytical layer queries the active release; the React client renders those returned values and provenance.</li></ol></div><div><h3 className="font-semibold text-ink">Limits of the current source</h3><ul className="mt-3 list-disc space-y-2 pl-5 text-sm leading-6 text-slate-700"><li>Sector and subsector are not verified source fields in the current release, so they are not presented as public analytics.</li><li>Numeric physical-progress percentages are not available and are never inferred from expenditure, dates or source status.</li><li>District / IDA preserves the supplied semantics and may identify an implementing authority rather than a conventional district.</li><li>Some records cannot be linked to a canonical work when the supplied source lacks a resolvable Work ID.</li></ul></div></div></section><section className="rounded-xl border border-blue-100 bg-blue-50 p-6"><h2 className="font-semibold text-ink">Explore responsibly</h2><p className="mt-2 max-w-3xl leading-7 text-slate-700">The interface supports public understanding, comparison and transparent review. It does not characterize source-quality issues as fraud or use analytical context as proof of wrongdoing.</p><Link to="/dashboard" className="button-primary mt-5">Explore the dashboard</Link></section></div>;
}
