import { useCallback, useState } from "react";
import { CheckCircle2, Database, FileWarning, HeartPulse, LockKeyhole, ShieldCheck } from "lucide-react";
import { api, ApiError } from "../api/client";
import type { AccessRequest, AdminDatasetRelease, AuthorizedUser, MonitoringRole } from "../api/types";
import { EmptyState, ErrorState, LoadingBlock } from "../components/DataState";
import { MetricCard } from "../components/MetricCard";
import { PageHeader } from "../components/PageHeader";
import { Pagination } from "../components/Pagination";
import { Panel } from "../components/Panel";
import { StatusBadge } from "../components/StatusBadge";
import { useApi } from "../hooks/useApi";
import { formatDateTime, formatInteger } from "../lib/format";

const roles: MonitoringRole[] = ["MP", "DISTRICT_AUTHORITY", "STATE_NODAL_AUTHORITY", "MINISTRY", "PLATFORM_ADMINISTRATOR"];

function adminError(error: Error, retry: () => void) {
  if (error instanceof ApiError && error.status === 401) return <ErrorState title="Administration sign-in required" error={new Error("Select an access profile. Every administration request is checked by the backend.")} onRetry={retry} />;
  if (error instanceof ApiError && error.status === 403) return <ErrorState title="Platform Administrator access required" error={new Error("The server denied this administration request. Your browser role is not sufficient on its own.")} onRetry={retry} />;
  return <ErrorState title="Unable to load administration data" error={error} onRetry={retry} />;
}

function ScopeFields({ role, values, setValues }: { role: MonitoringRole; values: { state_scope: string; district_scope: string; mp_scope: string }; setValues: (next: { state_scope: string; district_scope: string; mp_scope: string }) => void }) {
  if (role === "MINISTRY" || role === "PLATFORM_ADMINISTRATOR") return <p className="text-sm text-slate-600">This national or system role has no narrower monitoring scope.</p>;
  const key = role === "MP" ? "mp_scope" : role === "DISTRICT_AUTHORITY" ? "district_scope" : "state_scope";
  const label = role === "MP" ? "Authorized MP source name" : role === "DISTRICT_AUTHORITY" ? "Authorized District / IDA" : "Authorized State";
  return <label className="field-label">{label}<input className="field-control" value={values[key]} onChange={(event) => setValues({ state_scope: "", district_scope: "", mp_scope: "", [key]: event.target.value })} /></label>;
}

function AccessDecision({ request, onDone }: { request: AccessRequest; onDone: () => void }) {
  const [mode, setMode] = useState<"APPROVE" | "REJECT">("APPROVE");
  const [role, setRole] = useState<MonitoringRole>("STATE_NODAL_AUTHORITY");
  const [scope, setScope] = useState({ state_scope: request.state_name ?? "", district_scope: "", mp_scope: "" });
  const [note, setNote] = useState("");
  const [confirmed, setConfirmed] = useState(false);
  const [error, setError] = useState<Error>();
  const [saving, setSaving] = useState(false);
  const submit = async (event: React.FormEvent) => {
    event.preventDefault();
    if (!confirmed) return;
    setSaving(true); setError(undefined);
    try {
      if (mode === "APPROVE") await api.adminApproveAccessRequest(request.request_id, { role, ...scope, confirmation: "APPROVE", decision_note: note || undefined });
      else await api.adminRejectAccessRequest(request.request_id, { confirmation: "REJECT", decision_note: note });
      onDone();
    } catch (caught) { setError(caught instanceof Error ? caught : new Error("Unable to record the decision.")); } finally { setSaving(false); }
  };
  return <Panel title={`Decide request: ${request.name}`} className="mt-6" description="Approving creates an authorized-user record only with the role and scope selected here. It never self-assigns access.">
    <form className="grid gap-4 sm:grid-cols-2" onSubmit={submit}>
      <label className="field-label">Decision<select className="field-control" value={mode} onChange={(event) => { setMode(event.target.value as "APPROVE" | "REJECT"); setConfirmed(false); }}><option value="APPROVE">Approve and assign access</option><option value="REJECT">Reject request</option></select></label>
      {mode === "APPROVE" ? <><label className="field-label">Assigned role<select className="field-control" value={role} onChange={(event) => { const next = event.target.value as MonitoringRole; setRole(next); setScope({ state_scope: "", district_scope: "", mp_scope: "" }); setConfirmed(false); }}>{roles.map((item) => <option key={item}>{item}</option>)}</select></label><ScopeFields role={role} values={scope} setValues={setScope} /></> : <label className="field-label sm:col-span-2">Decision note<textarea className="field-control min-h-24" required value={note} onChange={(event) => setNote(event.target.value)} /></label>}
      {mode === "APPROVE" && <label className="field-label sm:col-span-2">Decision note (optional)<textarea className="field-control min-h-20" value={note} onChange={(event) => setNote(event.target.value)} /></label>}
      <label className="flex items-start gap-2 text-sm text-slate-700 sm:col-span-2"><input className="mt-1" type="checkbox" checked={confirmed} onChange={(event) => setConfirmed(event.target.checked)} />I confirm this {mode.toLowerCase()} decision and understand it will create an immutable audit event.</label>
      {error && <p className="text-sm text-red-800 sm:col-span-2" role="alert">{error.message}</p>}
      <button className="button-primary justify-self-start" type="submit" disabled={!confirmed || saving}>{saving ? "Saving…" : mode === "APPROVE" ? "Approve request" : "Reject request"}</button>
    </form>
  </Panel>;
}

export function AccessRequestsPage() {
  const [status, setStatus] = useState(""); const [search, setSearch] = useState(""); const [state, setState] = useState(""); const [district, setDistrict] = useState(""); const [createdFrom, setCreatedFrom] = useState(""); const [createdTo, setCreatedTo] = useState(""); const [page, setPage] = useState(1); const [selected, setSelected] = useState<AccessRequest>();
  const resetPage = () => setPage(1);
  const request = useCallback((signal: AbortSignal) => api.adminAccessRequests({ status: status || undefined, search: search || undefined, state: state || undefined, district: district || undefined, created_from: createdFrom ? `${createdFrom}T00:00:00Z` : undefined, created_to: createdTo ? `${createdTo}T23:59:59Z` : undefined, page }, signal), [status, search, state, district, createdFrom, createdTo, page]);
  const result = useApi(request, [request]);
  return <div><PageHeader eyebrow="Administration" title="Access requests" description="Pending access is reviewed by a Platform Administrator. A decision never grants a role or scope unless the administrator explicitly assigns it." />
    <section className="mb-6 grid gap-3 rounded-xl border border-line bg-white p-4 sm:grid-cols-2 xl:grid-cols-3"><label className="field-label">Status<select className="field-control" value={status} onChange={(event) => { setStatus(event.target.value); resetPage(); }}><option value="">All statuses</option><option>PENDING</option><option>APPROVED</option><option>REJECTED</option></select></label><label className="field-label">Search applicant<input className="field-control" value={search} onChange={(event) => { setSearch(event.target.value); resetPage(); }} /></label><label className="field-label">State<input className="field-control" value={state} onChange={(event) => { setState(event.target.value); resetPage(); }} /></label><label className="field-label">District / IDA<input className="field-control" value={district} onChange={(event) => { setDistrict(event.target.value); resetPage(); }} /></label><label className="field-label">Created from<input className="field-control" type="date" value={createdFrom} onChange={(event) => { setCreatedFrom(event.target.value); resetPage(); }} /></label><label className="field-label">Created to<input className="field-control" type="date" value={createdTo} onChange={(event) => { setCreatedTo(event.target.value); resetPage(); }} /></label></section>
    <Panel title="Requests" description="Real persisted access requests only. The empty state is an honest operational result.">{result.loading ? <LoadingBlock /> : result.error ? adminError(result.error, result.reload) : result.data ? <><div className="overflow-x-auto"><table className="min-w-[1000px] w-full text-left text-sm"><thead><tr className="border-b border-line text-xs uppercase text-slate-500"><th className="p-3">Applicant</th><th className="p-3">Office</th><th className="p-3">State</th><th className="p-3">District</th><th className="p-3">Requested</th><th className="p-3">Status</th><th className="p-3">Action</th></tr></thead><tbody>{result.data.items.map((item) => <tr key={item.request_id} className="border-b border-line/70"><td className="p-3"><p className="font-medium">{item.name}</p><p className="text-xs text-slate-500">{item.designation ?? "Not available"}</p></td><td className="p-3">{item.office ?? "Not available"}</td><td className="p-3">{item.state_name ?? "Not available"}</td><td className="p-3">{item.district_or_ida ?? "Not available"}</td><td className="p-3">{formatDateTime(item.created_at)}</td><td className="p-3"><StatusBadge value={item.status} /></td><td className="p-3">{item.status === "PENDING" ? <button className="button-secondary" onClick={() => setSelected(item)}>Review</button> : <span className="text-xs text-slate-500">Decision recorded</span>}</td></tr>)}</tbody></table></div>{!result.data.items.length && <EmptyState title="No access requests match the current filters." detail="No records are created merely to populate this administration page." />}{<Pagination page={result.data.pagination} onPageChange={setPage} />}</> : null}</Panel>
    {selected && <AccessDecision request={selected} onDone={() => { setSelected(undefined); result.reload(); }} />}
  </div>;
}

function UserAccessForm({ user, onDone }: { user: AuthorizedUser; onDone: () => void }) {
  const [role, setRole] = useState<MonitoringRole>(user.role); const [scope, setScope] = useState({ state_scope: user.state_scope ?? "", district_scope: user.district_scope ?? "", mp_scope: user.mp_scope ?? "" }); const [confirmed, setConfirmed] = useState(false); const [error, setError] = useState<Error>(); const [saving, setSaving] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!confirmed) return; setSaving(true); setError(undefined); try { await api.adminUpdateUser(user.user_id, { role, ...scope, expected_version: user.version, confirmation: "UPDATE_ACCESS" }); onDone(); } catch (caught) { setError(caught instanceof Error ? caught : new Error("Unable to update access.")); } finally { setSaving(false); } };
  const setStatus = async (confirmation: "DISABLE" | "REVOKE") => { if (!window.confirm(`${confirmation === "DISABLE" ? "Disable" : "Revoke"} this account? This action is audited.`)) return; try { const reason = window.prompt("Reason for this access action:"); if (!reason?.trim()) return; const action = confirmation === "DISABLE" ? api.adminDisableUser : api.adminRevokeUser; await action(user.user_id, { expected_version: user.version, confirmation, reason }); onDone(); } catch (caught) { setError(caught instanceof Error ? caught : new Error("Unable to change account status.")); } };
  return <Panel title={`Manage access: ${user.display_name}`} className="mt-6" description="Role and scope changes are server-validated and auditable."><form className="grid gap-4 sm:grid-cols-2" onSubmit={submit}><label className="field-label">Role<select className="field-control" value={role} onChange={(event) => { setRole(event.target.value as MonitoringRole); setScope({ state_scope: "", district_scope: "", mp_scope: "" }); setConfirmed(false); }}>{roles.map((item) => <option key={item}>{item}</option>)}</select></label><ScopeFields role={role} values={scope} setValues={setScope} /><label className="flex items-start gap-2 text-sm text-slate-700 sm:col-span-2"><input className="mt-1" type="checkbox" checked={confirmed} onChange={(event) => setConfirmed(event.target.checked)} />I confirm this role and scope update.</label>{error && <p className="text-sm text-red-800 sm:col-span-2" role="alert">{error.message}</p>}<div className="flex flex-wrap gap-2 sm:col-span-2"><button className="button-primary" type="submit" disabled={!confirmed || saving}>{saving ? "Saving…" : "Update access"}</button>{user.status === "ACTIVE" && <><button type="button" className="button-secondary" onClick={() => setStatus("DISABLE")}>Disable account</button><button type="button" className="button-secondary" onClick={() => setStatus("REVOKE")}>Revoke access</button></>}</div></form></Panel>;
}

export function UsersPage() {
  const [status, setStatus] = useState(""); const [role, setRole] = useState(""); const [page, setPage] = useState(1); const [selected, setSelected] = useState<AuthorizedUser>();
  const request = useCallback((signal: AbortSignal) => api.adminUsers({ status: status || undefined, role: role || undefined, page }, signal), [status, role, page]); const result = useApi(request, [request]);
  return <div><PageHeader eyebrow="Administration" title="Users & roles" description="Authorized-user records are created only by approved requests. Roles and scopes are exact server-side assignments; House is never a role." />
    <section className="mb-6 grid gap-3 rounded-xl border border-line bg-white p-4 sm:grid-cols-2"><label className="field-label">Account status<select className="field-control" value={status} onChange={(event) => { setStatus(event.target.value); setPage(1); }}><option value="">All statuses</option><option>ACTIVE</option><option>DISABLED</option><option>REVOKED</option></select></label><label className="field-label">Role<select className="field-control" value={role} onChange={(event) => { setRole(event.target.value); setPage(1); }}><option value="">All roles</option>{roles.map((item) => <option key={item}>{item}</option>)}</select></label></section>
    <Panel title="Authorized users" description="Access changes require an administrator actor, explicit confirmation, and an append-only audit event.">{result.loading ? <LoadingBlock /> : result.error ? adminError(result.error, result.reload) : result.data ? <><div className="overflow-x-auto"><table className="min-w-[1100px] w-full text-left text-sm"><thead><tr className="border-b border-line text-xs uppercase text-slate-500"><th className="p-3">User</th><th className="p-3">Role</th><th className="p-3">Scope</th><th className="p-3">Status</th><th className="p-3">Updated</th><th className="p-3">Action</th></tr></thead><tbody>{result.data.items.map((item) => <tr key={item.user_id} className="border-b border-line/70"><td className="p-3"><p className="font-medium">{item.display_name}</p><p className="text-xs text-slate-500">{item.office ?? "Not available"}</p></td><td className="p-3">{item.role.replaceAll("_", " ")}</td><td className="p-3">{item.state_scope ?? item.district_scope ?? item.mp_scope ?? "National / system"}</td><td className="p-3"><StatusBadge value={item.status} /></td><td className="p-3">{formatDateTime(item.updated_at)}</td><td className="p-3"><button className="button-secondary" onClick={() => setSelected(item)}>Manage</button></td></tr>)}</tbody></table></div>{!result.data.items.length && <EmptyState title="No authorized users match the current filters." detail="No users are fabricated for administration views." />}{<Pagination page={result.data.pagination} onPageChange={setPage} />}</> : null}</Panel>{selected && <UserAccessForm user={selected} onDone={() => { setSelected(undefined); result.reload(); }} />}</div>;
}

function ReleaseDetail({ release }: { release: AdminDatasetRelease }) { return <details><summary className="cursor-pointer text-blue">View 12 dataset assets and lifecycle</summary><div className="mt-3 overflow-x-auto"><table className="min-w-[980px] w-full text-left text-xs"><thead><tr className="border-b border-line text-slate-500"><th className="p-2">House</th><th className="p-2">Dataset</th><th className="p-2">Source</th><th className="p-2">Checksum</th><th className="p-2">Rows</th><th className="p-2">Validation</th></tr></thead><tbody>{release.datasets.map((asset) => <tr key={`${asset.house}-${asset.dataset_type}`} className="border-b border-line/70"><td className="p-2">{asset.house.replaceAll("_", " ")}</td><td className="p-2">{asset.dataset_type}</td><td className="p-2">{asset.source_filename} · {asset.source_sheet}</td><td className="max-w-48 truncate p-2 font-mono">{asset.source_checksum}</td><td className="p-2">{formatInteger(asset.source_row_count)} / {formatInteger(asset.valid_row_count)} valid</td><td className="p-2">{asset.warning_row_count} warnings · {asset.rejected_row_count} rejected</td></tr>)}</tbody></table></div><p className="mt-3 text-xs text-slate-500">Lifecycle events: {release.lifecycle_events.map((event) => `${event.event_type} · ${formatDateTime(event.occurred_at)}`).join("; ") || "None recorded"}</p></details>; }

export function DatasetsPage() {
  const [page, setPage] = useState(1);
  const requestVersions = useCallback((signal: AbortSignal) => api.adminDatasetVersions({ page }, signal), [page]);
  const versions = useApi(requestVersions, [requestVersions]); const active = useApi(useCallback((signal: AbortSignal) => api.adminActiveDataset(signal), []), []); const [message, setMessage] = useState<string>(); const [error, setError] = useState<Error>();
  const promote = async (release: AdminDatasetRelease) => { if (!window.confirm(`Promote ${release.release_version}? This changes the active release and is auditable.`)) return; try { await api.adminPromoteDataset(release.release_id, { confirmation: "PROMOTE" }); setMessage("Dataset release promoted."); versions.reload(); active.reload(); } catch (caught) { setError(caught instanceof Error ? caught : new Error("Unable to promote release.")); } };
  const rollback = async () => { if (!window.confirm("Roll back to the latest eligible historical release? This is a consequential, audited action.")) return; try { await api.adminRollbackDataset({ confirmation: "ROLLBACK" }); setMessage("Active dataset rolled back."); versions.reload(); active.reload(); } catch (caught) { setError(caught instanceof Error ? caught : new Error("Unable to roll back release.")); } };
  return <div><PageHeader eyebrow="Administration" title="Dataset versions" description="Read active-release provenance and lifecycle state. Promotion and rollback retain the Phase 6 approval gate and atomic active-release invariant." />{message && <p className="mb-4 rounded border border-blue-200 bg-blue-50 p-3 text-sm" role="status">{message}</p>}{error && <ErrorState error={error} />}
    {active.loading ? <LoadingBlock /> : active.error ? adminError(active.error, active.reload) : active.data ? <Panel title="Active release" description="One—and only one—release may be active."><dl className="grid gap-3 text-sm sm:grid-cols-3"><div><dt className="text-slate-500">Version</dt><dd className="font-medium">{active.data.release_version}</dd></div><div><dt className="text-slate-500">Promoted</dt><dd className="font-medium">{formatDateTime(active.data.promoted_at)}</dd></div><div><dt className="text-slate-500">Assets</dt><dd className="font-medium">{active.data.datasets.length} verified source metadata entries</dd></div></dl><div className="mt-4 flex flex-wrap gap-2"><button className="button-secondary" onClick={rollback}>Rollback active release</button></div></Panel> : null}
    <section className="mt-6"><Panel title="Release history" description="Source filenames, checksums, counts, validation status, and lifecycle entries come from persisted release records.">{versions.loading ? <LoadingBlock /> : versions.error ? adminError(versions.error, versions.reload) : versions.data ? <><div className="overflow-x-auto"><table className="min-w-[920px] w-full text-left text-sm"><thead><tr className="border-b border-line text-xs uppercase text-slate-500"><th className="p-3">Release</th><th className="p-3">Status</th><th className="p-3">Approved</th><th className="p-3">Promoted</th><th className="p-3">Assets</th><th className="p-3">Action</th></tr></thead><tbody>{versions.data.items.map((release) => <tr key={release.release_id} className="border-b border-line/70 align-top"><td className="p-3 font-medium">{release.release_version}</td><td className="p-3"><StatusBadge value={release.status} /></td><td className="p-3">{formatDateTime(release.approved_at)}</td><td className="p-3">{formatDateTime(release.promoted_at)}</td><td className="p-3"><ReleaseDetail release={release} /></td><td className="p-3">{release.status === "APPROVED" ? <button className="button-secondary" onClick={() => promote(release)}>Promote</button> : "—"}</td></tr>)}</tbody></table></div>{!versions.data.items.length && <EmptyState title="No dataset releases are available." detail="No version history is fabricated for this administration page." />}<Pagination page={versions.data.pagination} onPageChange={setPage} /></> : null}</Panel></section></div>;
}

export function DataQualityPage() {
  const [findingPage, setFindingPage] = useState(1);
  const findingsRequest = useCallback((signal: AbortSignal) => api.adminQualityFindings({ page: findingPage }, signal), [findingPage]);
  const quality = useApi(useCallback((signal: AbortSignal) => api.adminDataQuality(signal), []), []); const findings = useApi(findingsRequest, [findingsRequest]);
  const metrics = quality.data ? Object.entries(quality.data.metrics) : [];
  return <div><PageHeader eyebrow="Administration" title="Data quality" description="Real source-quality and validation metrics. These describe data completeness and traceability—not fraud or wrongdoing." />{quality.loading ? <LoadingBlock /> : quality.error ? adminError(quality.error, quality.reload) : quality.data ? <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(([label, value]) => <MetricCard key={label} label={label.replaceAll("_", " ")} value={typeof value === "boolean" ? (value ? "Available" : "Not available") : formatInteger(value)} description="Active-release source-quality metric." icon={FileWarning} />)}</div><p className="mt-4 text-xs text-slate-500">Active dataset release {quality.data.dataset_version} · calculated {formatDateTime(quality.data.generated_at)}</p></> : null}
    <section className="mt-6"><Panel title="Validation findings" description="Server-paginated, safe metadata drill-down. Raw source rows are not exposed.">{findings.loading ? <LoadingBlock /> : findings.error ? adminError(findings.error, findings.reload) : findings.data ? <><div className="overflow-x-auto"><table className="min-w-[860px] w-full text-left text-sm"><thead><tr className="border-b border-line text-xs uppercase text-slate-500"><th className="p-3">Severity</th><th className="p-3">Code</th><th className="p-3">Field</th><th className="p-3">Source row</th><th className="p-3">Message</th></tr></thead><tbody>{findings.data.items.map((row) => <tr key={row.finding_id} className="border-b border-line/70"><td className="p-3"><StatusBadge value={row.severity} /></td><td className="p-3">{row.code}</td><td className="p-3">{row.field_name ?? "Not available"}</td><td className="p-3">{row.source_row_number}</td><td className="p-3">{row.message}</td></tr>)}</tbody></table></div>{!findings.data.items.length && <EmptyState title="No validation findings are available for the active release." />}<Pagination page={findings.data.pagination} onPageChange={setFindingPage} /></> : null}</Panel></section></div>;
}

export function AuditLogsPage() {
  const [actor, setActor] = useState(""); const [eventType, setEventType] = useState(""); const [entity, setEntity] = useState(""); const [dateFrom, setDateFrom] = useState(""); const [dateTo, setDateTo] = useState(""); const [page, setPage] = useState(1);
  const resetPage = () => setPage(1);
  const request = useCallback((signal: AbortSignal) => api.adminAuditLogs({ actor: actor || undefined, event_type: eventType || undefined, entity: entity || undefined, date_from: dateFrom ? `${dateFrom}T00:00:00Z` : undefined, date_to: dateTo ? `${dateTo}T23:59:59Z` : undefined, page }, signal), [actor, eventType, entity, dateFrom, dateTo, page]); const result = useApi(request, [request]);
  return <div><PageHeader eyebrow="Administration" title="Audit logs" description="Append-only records from access administration, dataset lifecycle, review workflow, recommendations, and privacy-minimized Ask AI metadata." /><section className="mb-6 grid gap-3 rounded-xl border border-line bg-white p-4 sm:grid-cols-2 xl:grid-cols-3"><label className="field-label">Actor<input className="field-control" value={actor} onChange={(event) => { setActor(event.target.value); resetPage(); }} /></label><label className="field-label">Event type<input className="field-control" value={eventType} onChange={(event) => { setEventType(event.target.value); resetPage(); }} /></label><label className="field-label">Entity ID or type<input className="field-control" value={entity} onChange={(event) => { setEntity(event.target.value); resetPage(); }} /></label><label className="field-label">From<input className="field-control" type="date" value={dateFrom} onChange={(event) => { setDateFrom(event.target.value); resetPage(); }} /></label><label className="field-label">To<input className="field-control" type="date" value={dateTo} onChange={(event) => { setDateTo(event.target.value); resetPage(); }} /></label></section>
    <Panel title="Operational audit trail" description="Historical entries cannot be edited from this API.">{result.loading ? <LoadingBlock /> : result.error ? adminError(result.error, result.reload) : result.data ? <><div className="overflow-x-auto"><table className="min-w-[960px] w-full text-left text-sm"><thead><tr className="border-b border-line text-xs uppercase text-slate-500"><th className="p-3">Time</th><th className="p-3">Source</th><th className="p-3">Event</th><th className="p-3">Entity</th><th className="p-3">Actor</th><th className="p-3">Safe metadata</th></tr></thead><tbody>{result.data.items.map((row) => <tr key={`${row.source}-${row.audit_id}`} className="border-b border-line/70"><td className="p-3">{formatDateTime(row.occurred_at)}</td><td className="p-3">{row.source}</td><td className="p-3">{row.event_type}</td><td className="p-3">{row.entity_type} · {row.entity_id}</td><td className="p-3">{row.actor}</td><td className="p-3"><pre className="max-w-56 overflow-auto text-xs">{JSON.stringify(row.metadata)}</pre></td></tr>)}</tbody></table></div>{!result.data.items.length && <EmptyState title="No audit entries match the current filters." />}{<Pagination page={result.data.pagination} onPageChange={setPage} />}</> : null}</Panel></div>;
}

export function SystemHealthPage() {
  const system = useApi(useCallback((signal: AbortSignal) => api.adminSystem(signal), []), []); const configuration = useApi(useCallback((signal: AbortSignal) => api.adminConfiguration(signal), []), []);
  if (system.loading || configuration.loading) return <LoadingBlock label="Checking live platform health…" />;
  if (system.error) return adminError(system.error, system.reload); if (configuration.error) return adminError(configuration.error, configuration.reload); if (!system.data || !configuration.data) return null;
  const safe = configuration.data;
  return <div><PageHeader eyebrow="Administration" title="System health" description="Live operational status only. Secrets, environment values, database connection strings, and provider credentials are never returned." /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="API" value={system.data.api_status} description="Protected API availability." icon={HeartPulse} /><MetricCard label="Database" value={system.data.database_status} description="Live database connectivity." icon={Database} /><MetricCard label="Active dataset" value={system.data.active_dataset_status} description={system.data.active_release_version ?? "No active release"} icon={CheckCircle2} /><MetricCard label="Gemini provider" value={system.data.gemini_status} description={system.data.gemini_model ?? "No model configured"} icon={ShieldCheck} /></div><section className="mt-6 grid gap-6 xl:grid-cols-2"><Panel title="Runtime state"><dl className="grid gap-4 text-sm sm:grid-cols-2"><div><dt className="text-slate-500">Application version</dt><dd className="font-medium">{system.data.application_version}</dd></div><div><dt className="text-slate-500">Migration</dt><dd className="font-medium">{system.data.migration_version ?? "Not available"}</dd></div><div><dt className="text-slate-500">Environment</dt><dd className="font-medium">{system.data.app_environment}</dd></div><div><dt className="text-slate-500">Checked</dt><dd className="font-medium">{formatDateTime(system.data.checked_at)}</dd></div></dl>{system.data.latest_analytics_run && <p className="mt-4 text-sm text-slate-700">Latest analytics run: <strong>{system.data.latest_analytics_run.status}</strong> · {system.data.latest_analytics_run.dataset_version}</p>}</Panel><Panel title="Safe production configuration"><dl className="grid gap-3 text-sm sm:grid-cols-2">{Object.entries(safe).filter(([key]) => key !== "checked_at").map(([key, value]) => <div key={key} className="rounded bg-slate-50 p-3"><dt className="text-xs uppercase text-slate-500">{key.replaceAll("_", " ")}</dt><dd className="mt-1 font-medium">{String(value)}</dd></div>)}</dl><p className="mt-4 flex items-center gap-2 text-xs text-slate-500"><LockKeyhole className="size-3.5" aria-hidden="true" />Configuration values and secrets remain environment-managed and are not editable here.</p></Panel></section></div>;
}

export const ConfigurationPage = SystemHealthPage;
