"""Add persisted protected monitoring intelligence outputs.

Revision ID: 20260907_03
Revises: 20260906_02
"""
from alembic import op
import sqlalchemy as sa

revision = "20260907_03"
down_revision = "20260906_02"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table("analytics_runs", sa.Column("run_id", sa.String(64), primary_key=True), sa.Column("dataset_version", sa.String(96), nullable=False), sa.Column("batch_id", sa.String(64), nullable=False), sa.Column("started_at", sa.DateTime(timezone=True), nullable=False), sa.Column("completed_at", sa.DateTime(timezone=True)), sa.Column("status", sa.String(16), nullable=False), sa.Column("rules_version", sa.String(32), nullable=False), sa.Column("model_version", sa.String(32), nullable=False), sa.Column("duplicate_engine_version", sa.String(32), nullable=False), sa.Column("feature_version", sa.String(32), nullable=False), sa.Column("model_config", sa.JSON(), nullable=False), sa.Column("record_counts", sa.JSON(), nullable=False), sa.Column("signal_counts", sa.JSON(), nullable=False), sa.Column("alert_count", sa.Integer(), nullable=False, server_default="0"), sa.Column("error_summary", sa.Text()))
    for name, columns in [("ix_analytics_runs_dataset_version", ["dataset_version"]), ("ix_analytics_runs_batch_id", ["batch_id"]), ("ix_analytics_runs_started_at", ["started_at"]), ("ix_analytics_runs_status", ["status"])]: op.create_index(name, "analytics_runs", columns)
    op.create_table("monitoring_signals", sa.Column("signal_id", sa.String(80), primary_key=True), sa.Column("run_id", sa.String(64), sa.ForeignKey("analytics_runs.run_id"), nullable=False), sa.Column("dataset_version", sa.String(96), nullable=False), sa.Column("work_key", sa.String(110), sa.ForeignKey("works.canonical_work_key"), nullable=False), sa.Column("house", sa.String(20), nullable=False), sa.Column("state_name", sa.String(150)), sa.Column("district_or_ida", sa.String(500)), sa.Column("mp_source_name", sa.String(300)), sa.Column("category", sa.String(32), nullable=False), sa.Column("rule_id", sa.String(80), nullable=False), sa.Column("severity", sa.String(16), nullable=False), sa.Column("points", sa.Integer(), nullable=False, server_default="0"), sa.Column("title", sa.String(240), nullable=False), sa.Column("explanation", sa.Text(), nullable=False), sa.Column("evidence", sa.JSON(), nullable=False), sa.Column("fingerprint", sa.String(64), nullable=False), sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("fingerprint", name="uq_monitoring_signal_fingerprint"))
    op.create_table("duplicate_candidates", sa.Column("candidate_id", sa.String(80), primary_key=True), sa.Column("run_id", sa.String(64), sa.ForeignKey("analytics_runs.run_id"), nullable=False), sa.Column("dataset_version", sa.String(96), nullable=False), sa.Column("work_a_key", sa.String(110), sa.ForeignKey("works.canonical_work_key"), nullable=False), sa.Column("work_b_key", sa.String(110), sa.ForeignKey("works.canonical_work_key"), nullable=False), sa.Column("similarity_score", sa.Float(), nullable=False), sa.Column("review_priority", sa.String(16), nullable=False), sa.Column("contextual_comparison", sa.JSON(), nullable=False), sa.Column("reason", sa.Text(), nullable=False), sa.Column("fingerprint", sa.String(64), nullable=False), sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("fingerprint", name="uq_duplicate_candidate_fingerprint"))
    op.create_table("risk_assessments", sa.Column("assessment_id", sa.String(80), primary_key=True), sa.Column("run_id", sa.String(64), sa.ForeignKey("analytics_runs.run_id"), nullable=False), sa.Column("dataset_version", sa.String(96), nullable=False), sa.Column("work_key", sa.String(110), sa.ForeignKey("works.canonical_work_key"), nullable=False), sa.Column("house", sa.String(20), nullable=False), sa.Column("state_name", sa.String(150)), sa.Column("district_or_ida", sa.String(500)), sa.Column("mp_source_name", sa.String(300)), sa.Column("raw_score", sa.Integer(), nullable=False), sa.Column("normalized_score", sa.Float(), nullable=False), sa.Column("risk_band", sa.String(16), nullable=False), sa.Column("component_scores", sa.JSON(), nullable=False), sa.Column("evidence", sa.JSON(), nullable=False), sa.Column("data_quality_context", sa.JSON(), nullable=False), sa.Column("rules_version", sa.String(32), nullable=False), sa.Column("model_version", sa.String(32), nullable=False), sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("dataset_version", "work_key", name="uq_risk_assessment_dataset_work"))
    op.create_table("analytical_alerts", sa.Column("alert_id", sa.String(80), primary_key=True), sa.Column("run_id", sa.String(64), sa.ForeignKey("analytics_runs.run_id"), nullable=False), sa.Column("dataset_version", sa.String(96), nullable=False), sa.Column("work_key", sa.String(110), sa.ForeignKey("works.canonical_work_key"), nullable=False), sa.Column("house", sa.String(20), nullable=False), sa.Column("category", sa.String(32), nullable=False), sa.Column("severity", sa.String(16), nullable=False), sa.Column("title", sa.String(240), nullable=False), sa.Column("explanation", sa.Text(), nullable=False), sa.Column("evidence", sa.JSON(), nullable=False), sa.Column("status", sa.String(24), nullable=False, server_default="OPEN"), sa.Column("fingerprint", sa.String(64), nullable=False), sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("fingerprint", name="uq_analytical_alert_fingerprint"))
    for table in ["monitoring_signals", "duplicate_candidates", "risk_assessments", "analytical_alerts"]:
        for column in {"monitoring_signals": ["run_id", "dataset_version", "work_key", "house", "state_name", "district_or_ida", "mp_source_name", "category", "rule_id", "severity", "fingerprint", "generated_at"], "duplicate_candidates": ["run_id", "dataset_version", "work_a_key", "work_b_key", "review_priority", "fingerprint", "generated_at"], "risk_assessments": ["run_id", "dataset_version", "work_key", "house", "state_name", "district_or_ida", "mp_source_name", "risk_band", "generated_at"], "analytical_alerts": ["run_id", "dataset_version", "work_key", "house", "category", "severity", "status", "fingerprint", "generated_at"]}[table]: op.create_index(f"ix_{table}_{column}", table, [column])


def downgrade() -> None:
    op.drop_table("analytical_alerts")
    op.drop_table("risk_assessments")
    op.drop_table("duplicate_candidates")
    op.drop_table("monitoring_signals")
    op.drop_table("analytics_runs")
