import { Activity, AlertTriangle, BarChart3, Bell, ClipboardCheck, GitCompareArrows, Landmark, Scale, ShieldCheck, Timer, Lightbulb, LayoutDashboard, Bot } from "lucide-react";
import { NavLink, Outlet } from "react-router-dom";
import { DevelopmentAccessForm, useMonitoringAccess } from "../monitoring/MonitoringAccess";
import { api } from "../api/client";
import { useApi } from "../hooks/useApi";
import { useCallback } from "react";

const links = [["Monitoring Overview", "/monitoring", ShieldCheck], ["Risk", "/monitoring/risk", Activity], ["Anomalies", "/monitoring/anomalies", BarChart3], ["Alerts", "/monitoring/alerts", AlertTriangle], ["Potential Duplicates", "/monitoring/duplicates", GitCompareArrows], ["Financial", "/monitoring/financial", Landmark], ["Lifecycle", "/monitoring/lifecycle", Timer], ["Reviews", "/monitoring/reviews", ClipboardCheck], ["Ask AI", "/monitoring/ai", Bot], ["Peer comparison", "/monitoring/benchmarking", Scale], ["Recommendations", "/monitoring/recommendations", Lightbulb], ["Executive", "/monitoring/executive", LayoutDashboard]] as const;

export function MonitoringShell() {
  const { credentials, setCredentials } = useMonitoringAccess();
  const notifications = useApi(useCallback((signal: AbortSignal) => api.notifications(signal), []), []);
  if (!credentials) return <DevelopmentAccessForm />;
  const unread = notifications.data?.filter((item) => item.state === "UNREAD").length ?? 0;
  return <div><section className="mb-7 overflow-hidden rounded-lg border border-blue-100 bg-white shadow-sm" aria-label="Authorized monitoring context"><div className="gov-rule h-0.5" aria-hidden="true" /><div className="flex flex-wrap items-center justify-between gap-4 bg-blue-50/70 px-5 py-4"><div><p className="eyebrow">Authorized monitoring</p><p className="mt-1 text-lg font-semibold text-ink">Anomaly, fraud-risk and inefficiency monitoring</p><p className="mt-2 text-sm text-slate-700">Development/prototype access profile: <span className="font-semibold text-ink">{credentials.role.replaceAll("_", " ")}</span>. Signals are decision support; server authorization and scope enforcement remain authoritative.</p></div><div className="flex items-center gap-3"><div className="flex items-center gap-1.5 text-sm text-slate-700" aria-label={`${unread} unread notifications`}><Bell className="size-4 text-blue" aria-hidden="true" />{unread} unread</div><button type="button" className="button-secondary" onClick={() => setCredentials()}>Sign out</button></div></div></section><nav className="mb-7 flex gap-2 overflow-x-auto border-b border-line pb-3" aria-label="Monitoring navigation">{links.map(([label, to, Icon]) => <NavLink key={to} to={to} end={to === "/monitoring"} className={({ isActive }) => `inline-flex shrink-0 items-center gap-1.5 rounded-md px-3 py-2 text-sm font-medium transition ${isActive ? "bg-navy text-white shadow-sm" : "border border-line bg-white text-slate-700 hover:border-blue hover:bg-blue-50 hover:text-blue"}`}><Icon className="size-4" aria-hidden="true" />{label}</NavLink>)}</nav>{notifications.data?.length ? <aside className="mb-6 rounded-lg border border-line bg-white p-4 shadow-sm" aria-label="Recent notifications"><p className="font-semibold text-ink">Recent monitoring notifications</p><ul className="mt-2 space-y-2 text-sm text-slate-700">{notifications.data.slice(0, 3).map((item) => <li key={item.notification_id}>{item.message} <span className="text-slate-500">({item.state.toLowerCase()})</span></li>)}</ul></aside> : null}<Outlet /></div>;
}
